// AUTO-GENERATED route table.
export interface PageMeta { slug: string; name: string; title: string; description: string }
export const PAGES: PageMeta[] = [
  { slug: "", name: "Home", title: "Lemur Legal \u2014 Law for crypto, fintech, startups, deep tech &amp; dual-use", description: "Lemur Legal is a specialist tech-law office in Ljubljana. One firm, three practices: crypto &amp; fintech (MiCA, tokens, licensing), startups &amp; deep tech (incorporation, IP, contracts), and an emerging defence &amp; dual-use practice. Founded by Peter Merc, Ph.D." },
  { slug: "mica-white-paper", name: "MiCAWhitePaper", title: "MiCA White Paper \u2014 Lemur Legal", description: "A MiCA-compliant white paper, drafted and filed. Every token issuer targeting EU investors needs a MiCA white paper and legal documentation \u2014 Lemur Legal handles drafting through to regulator filing." },
  { slug: "crypto-legal-opinion", name: "CryptoLegalOpinion", title: "Crypto Legal Opinion \u2014 Lemur Legal", description: "The legal opinion that gets your token listed \u2014 reasoned, classified and accepted under MiCA and EU law. First draft in 48 hours." },
  { slug: "regulatory-compliance", name: "RegulatoryCompliance", title: "Regulatory Compliance \u2014 Lemur Legal", description: "Your outsourced compliance function. We act as your external compliance officer across PSD2, MiFID II, EBA guidelines, MiCA and EU AML rules." },
  { slug: "incorporation-esop", name: "IncorporationESOP", title: "Incorporation &amp; ESOP \u2014 Lemur Legal", description: "Set up your company and incentivise your team. From the right legal form to employee option plans (ESOP), Lemur Legal puts the legal foundations of your startup in place from day one." },
  { slug: "ip-protection", name: "IPProtection", title: "IP Protection \u2014 Lemur Legal", description: "Protect and defend your intellectual property. IPR strategy, trademark and design registration (EUIPO representative), copyright, contracts and licensing \u2014 from Lemur Legal." },
  { slug: "startups-contracts", name: "ContractsCommercial", title: "Contracts &amp; Commercial \u2014 Lemur Legal", description: "The contracts that protect your business. From software and source-code licences to manufacturing and partnership deals, Lemur Legal drafts the agreements that remove risk from every relationship your technology company enters." },
  { slug: "regulatory-qualification", name: "RegulatoryQualification", title: "Trade Regulatory Qualification \u2014 Lemur Legal", description: "Defence &amp; dual-use technology, cleared for global markets. Lemur Legal turns export controls, sanctions and customs classification into clear, repeatable cross-border workflows for products, components and technologies." },
  { slug: "investment-readiness-review", name: "InvestmentReadiness", title: "Investment Readiness Review \u2014 Lemur Legal", description: "Prove your defence or dual-use company is investment-ready and de-risk the deal. Lemur Legal scores your regulatory exposure, compliance maturity and operational readiness for fundraising, M&amp;A and diligence." },
  { slug: "compliance-frameworks", name: "ComplianceFrameworks", title: "Compliance Frameworks \u2014 Lemur Legal", description: "Turn defence &amp; dual-use regulatory complexity into audit-ready operations. Lemur Legal builds scalable compliance frameworks, governance and controls across export controls, sanctions and procurement." },
  { slug: "blog", name: "Blog", title: "Blog \u2014 Lemur Legal", description: "Briefings, explainers and deep-dives on EU tech law \u2014 MiCA and tokens, startup and IP law, and export controls \u2014 from Lemur Legal, a specialist tech-law office in Ljubljana." },
  { slug: "media", name: "MediaCoverage", title: "Media Coverage \u2014 Lemur Legal", description: "Interviews, commentary and press coverage featuring Lemur Legal across Slovenian and international media \u2014 on MiCA, crypto regulation, startups and the law behind emerging technology." },
  { slug: "contact", name: "Contact", title: "Contact \u2014 Lemur Legal", description: "Tell us what you're building. Send a brief to Lemur Legal \u2014 a specialist tech-law office in Ljubljana for crypto &amp; fintech, startups &amp; deep tech, and defence &amp; dual-use. Fixed fee, reply within 24 hours." },
  { slug: "terms-of-use", name: "TermsOfUse", title: "Terms of Use &amp; Privacy Policy \u2014 Lemur Legal", description: "Terms of use of the Lemur Legal website and how we process the personal data of visitors and users, in line with the GDPR and the Slovenian ZVOP-2." },
]
