// AUTO-GENERATED route table.
export interface PageMeta { slug: string; name: string; title: string; description: string }
export const PAGES: PageMeta[] = [
  { slug: "", name: "Home", title: "Lemur Legal \u2014 Law for crypto, fintech, startups, deep tech &amp; dual-use", description: "Lemur Legal is a specialist tech-law firm in Ljubljana. One firm, three practices: crypto &amp; fintech (MiCA, tokens, licensing), startups &amp; deep tech (incorporation, IP, contracts), and an emerging defence &amp; dual-use practice. Founded by Peter Merc, Ph.D." },
  { slug: "mica_white_paper", name: "MiCAWhitePaper", title: "MiCA White Paper \u2014 Lemur Legal", description: "A MiCA-compliant white paper, drafted and filed. Every token issuer targeting EU investors needs a MiCA white paper and legal documentation \u2014 Lemur Legal handles drafting through to regulator filing." },
  { slug: "crypto_legal_opinion", name: "CryptoLegalOpinion", title: "Crypto Legal Opinion \u2014 Lemur Legal", description: "The legal opinion that gets your token listed \u2014 reasoned, classified and accepted under MiCA and EU law. First draft in 48 hours." },
  { slug: "regulatory_compliance", name: "RegulatoryCompliance", title: "Regulatory Compliance \u2014 Lemur Legal", description: "Your outsourced compliance function. We act as your external compliance officer across PSD2, MiFID II, EBA guidelines, MiCA and EU AML rules." },
  { slug: "incorporation_esop", name: "IncorporationESOP", title: "Incorporation &amp; ESOP \u2014 Lemur Legal", description: "Set up your company and incentivise your team. From the right legal form to employee option plans (ESOP), Lemur Legal puts the legal foundations of your startup in place from day one." },
  { slug: "ip_protection", name: "IPProtection", title: "IP Protection \u2014 Lemur Legal", description: "Protect and defend your intellectual property. IPR strategy, trademark and design registration (EUIPO representative), copyright, contracts and licensing \u2014 from Lemur Legal." },
  { slug: "startups_contracts", name: "ContractsCommercial", title: "Contracts &amp; Commercial \u2014 Lemur Legal", description: "The contracts that protect your business. From software and source-code licences to manufacturing and partnership deals, Lemur Legal drafts the agreements that remove risk from every relationship your technology company enters." },
  { slug: "regulatory_qualification", name: "RegulatoryQualification", title: "Trade Regulatory Qualification \u2014 Lemur Legal", description: "Reach global markets without regulatory friction. Lemur Legal qualifies dual-use technology under export controls, customs and sanctions \u2014 turning trade regulation into repeatable, scalable workflows." },
  { slug: "investment_readiness_review", name: "InvestmentReadiness", title: "Investment Readiness Review \u2014 Lemur Legal", description: "Prove you're investment-ready and de-risk the deal. Lemur Legal scores your regulatory exposure, compliance maturity and operational readiness for fundraising, M&amp;A and market entry in defence and dual-use." },
  { slug: "compliance_frameworks", name: "ComplianceFrameworks", title: "Compliance Frameworks \u2014 Lemur Legal", description: "Turn regulatory complexity into audit-ready operations. Lemur Legal builds scalable compliance frameworks, governance and control systems for defence and dual-use technology companies." },
  { slug: "blog", name: "Blog", title: "Blog \u2014 Lemur Legal", description: "Briefings, explainers and deep-dives on EU tech law \u2014 MiCA and tokens, startup and IP law, and export controls \u2014 from Lemur Legal, a specialist tech-law firm in Ljubljana." },
  { slug: "contact", name: "Contact", title: "Contact \u2014 Lemur Legal", description: "Tell us what you're building. Send a brief to Lemur Legal \u2014 a specialist tech-law firm in Ljubljana for crypto &amp; fintech, startups &amp; deep tech, and defence &amp; dual-use. Fixed fee, reply within 24 hours." },
]
